### ISSUE TITLE
Performance and logging

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/girder_assetstore#12]
I started importing a large collection from another girder server.  As large_image scanned files, it was quite slow for downloads (there was a collection of 10,000 netcdf files that were the main issue).  Part of this is excessive file download logging.  We can throttle download logging by adding 
```
from girder.api import filter_logging

filter_logging.addLoggingFilter(
            'GET (/[^/ ?#]+)*/file/[^/ ?#]+/download\?offset',
            frequency=250, duration=10)
```
Which at least will log partial downloads only every 250 requests or once per 10 seconds (whichever is more frequent).

**Comment by willdunklin** [comment]
@manthey Added the snippet above. Looks like the code formatting changed a character in the filter string, it didn't like that you were trying to escape the `?`. You can see the line here: https://github.com/DigitalSlideArchive/girder_assetstore/pull/14/files#diff-be93d1e8f60da79ba708e5600559d724220b285f5bef58a327d37e70eb06d632R18
Wanted to confirm that this was acceptable, or if it needed to be changed.

**Comment by manthey** [comment]
That looks fine.
